pipeline {
    agent any
    
    environment {
        JAVA_HOME = "/usr/lib/jvm/java-17-openjdk-amd64"
    }

    stages {
        stage('Checkout') {
            steps {
                script {
                    git branch: "main", credentialsId: "conf-git", url: "https://github.com/venh312/msa-issuemoa.git"
                }
            }
        }
        stage('Build') {
            steps {
                script {
                    sh "chmod 777 gradlew"
                    sh "./gradlew clean build"
                }
            }
        }
        stage('Docker Image Build') {
            steps {
                dir('service-batch') {
                    sh "docker build -t msa-issuemoa-discovery ."
                }
            }
        }
        stage('Docker Run Container') {
            steps {
                script {
                    def containerRunning = sh(script: 'docker inspect -f \'{{.State.Running}}\' msa-issuemoa-discovery 2>/dev/null', returnStatus: true) == 0

                    if (containerRunning) {
                        echo 'Container is already running'
                        sh "docker stop msa-issuemoa-discovery"
                        sh "docker rm msa-issuemoa-discovery"
                    }
                    
                    sh "docker run -d --name msa-issuemoa-discovery -p 8761:8761 --network issuemoa msa-issuemoa-discovery"
                }
            }
        }
    }
}
