server:
  port: 30010
spring:
  application:
    name: issueMoaBatch
  config:
    import: optional:configserver:http://192.168.219.101:38888
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
logging:
  level:
    root: info

eureka:
  client:
    enabled: false