server:
  port: 30010
spring:
  application:
    name: issueMoaBatch
  config:
    import: optional:configserver:http://issuemoa-config:38888
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
logging:
  level:
    root: info

eureka:
  client:
    serviceUrl:
      defaultZone: http://msa-issuemoa-discovery:38761/eureka
