server:
  port: 38000
spring:
  application:
    name: issueMoaGateway
  kafka:
    bootstrap-servers: kafka:9092
eureka:
  client:
    serviceUrl:
      defaultZone: http://msa-issuemoa-discovery:38761/eureka