server:
  port: 17060
spring:
  config:
    import:
      - optional:configserver:http://issuemoa-config:8888
  kafka:
    bootstrap-servers: 192.168.0.31:9092
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://issuemoa-eureka:8761/eureka