spring:
  application:
    name: issueMoaMail
  config:
    import:
      - optional:configserver:http://issuemoa-config:8888
  kafka:
    bootstrap-servers: 192.168.0.31:9092
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info, metrics, prometheus
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://msa-issuemoa-discovery:8761/eureka