spring:
  application:
    name: issueMoaMail
  config:
    import:
      - optional:configserver:http://61.102.114.235:8888
  kafka:
    bootstrap-servers: 192.168.219.101:9092
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info, metrics, prometheus
eureka:
  client:
    enabled: false