server:
  port: 37090
spring:
  application:
    name: issueMoaStore
  config:
    import:
      - optional:configserver:http://issuemoa/config:38888
eureka:
  client:
    serviceUrl:
      defaultZone: http://msa-issuemoa-discovery:38761/eureka
