server:
  port: 37070
spring:
  application:
    name: issueMoaUsers
  config:
    import:
      - optional:configserver:http://issuemoa/config:38888
eureka:
  client:
    serviceUrl:
      defaultZone: http://msa-issuemoa-discovery:38761/eureka
